# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives
  

# Miscelaneous
favicon: /favicon.png

# stylesheets loaded in the <head>
stylesheets:
- /css/pteris.css

# scripts loaded in the end of the body
scripts:
- /js/pteris.js

# helping search engine to better understand your site.
keywords: pteris

# the large image in the front of index page.
headerImageUrl:

# your avatar representing in the header of index page
avatar:

# title represented in the header of index page.
title:

# description represented in the header of the index page.
description:
